# Generated by Django 4.0.4 on 2022-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_age', models.IntegerField()),
                ('s_address', models.TextField()),
                ('s_joining_date', models.DateField()),
                ('s_email_id', models.CharField(max_length=50)),
                ('s_qualifications', models.CharField(max_length=50)),
                ('s_gender', models.CharField(max_length=50)),
                ('s_phone', models.IntegerField()),
            ],
        ),
    ]
