# Generated by Django 4.0.4 on 2022-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='s_phone',
            field=models.CharField(max_length=12),
        ),
    ]
